### ISSUE TITLE
Use with Dataloaders

### ISSUE THREAD

**Issue by tallpaul-embark** [gthau/graphql-error-handling-with-union-and-fpts#2]
I love the concept and thought process of the article and how this was laid out here. I am having an issue with typing in terms of returning a TaskEither through a dataloader, and not sure if it is possible or if that is the time to turn it from an Either to just a Task. Do you have any thoughts?

**Comment by gthau** [comment]
Hi,

I implemented some examples of use of Dataloader with fp-ts, you can see the changes here: https://github.com/gthau/graphql-error-handling-with-union-and-fpts/compare/8f3c5219ad1d0befcd8e2fa1720faaadb826474e..HEAD?diff=unified

The Dataloader `loadMany` has a return type of `Promise<Array<Value | Error>>` (same for the `BatchLoadFn` used to fetch the data). So we must implement the `batchLoadFn` to return the same type (and the values/errors must match the order of the `keys` parameter).
In the `batchLoadFn`, we can have 2 cases: either the API we use to fetch data (ORM, gRPC, REST, any SDK) supports fetching several entities in one call, or it doesn't (in this case you'll have to make one call to the API for each key passed to the `batchLoadFn`).

In the first scenario (API supports batching), you can make a function:
- that makes one call to your API, this function returns:
  - a `TaskEither<CallError, Array<Either<DomainError, Entity>>>` which you then transform into
    - a `Task<Array<Either<CallError | DomainError, Entity>>>`
    - then `Task<Array<CallError | DomainError | Entity>>`
    - then `Promise<Array<CallError | DomainError | Entity>>`.
==> you can look at the `entities` query

In the second scenario (API doesn't support batching), you can make a function:
- that returns a `Array<TaskEither<DomainError | CallError, Entity>>`
- which you transform into a `Array<Task<DomainError | CallError | Entity>>`
- then `Task<Array<DomainError | CallError | Entity>>`
- then `Promise<Array<DomainError | CallError | Entity>>`.
===> you can look at the `users` query

Then in the resolvers where you call the dataloader, it needs to map the error values to "wrapped errors" so the Errors type resolvers can work properly.

**Comment by tallpaul-embark** [comment]
Thanks for sharing this! It has been very enlightening.
